shreyas-a/awesome-developers

- developers.json
This patch adds a new profile based on #4
> Adding new profile

- developers.json
> added my information

- developers.json
> add dev details to developers.json file

- developers.json
> add my detail

- developers.json
I also converted all Javascript to JavaScript.
> add changhc to developers list

- developers.json
> Add SloRunner to developers list

- developers.json
Adding myself to the developers list. Happy Hacktoberfest :)
> Add Sunny Singh to developers list

- developers.json
Add Raju Vishwas to developers list
> #4 - Add Raju Vishwas to developers list

- developers.json
Add dev name to developers.json file :)
> Add developer details to developers.json

- developers.json
> feat (adding-new_profile) #4

- developers.json
This patch adds a new profile based on #4
Code review please @shreyas-a
> Add RiKap to developers list

- developers.json
Thank you for letting me add my username. Happy coding
> added my username to json file

- developers.json
Hi, thank you for your repo, could you please review my PR ?
> Add XtheWiz detail into developers.json

- developers.json
> Add my personal information

- developers.json
Added Jose Almaraz to developers list.
> Add Jose Almaraz to developers list

- developers.json
> added name

- developers.json
Thanks for having this fun list 👍
> Add jack howard name

- developers.json
> (feat) add ikhsanalatsary GH username

- developers.json
Add my profile in developers.json
> add my profile

- .gitignore
- developers.json
Added my data to the developers.json
> contribution

- developers.json
Added myself to the developer.json file. I am number 1140.
> added my own dev creds

- developers.json
Include myself in developers file
> include myself

- developers.json
Added myself to the awesome list of devs.
> Added myself

- developers.json
Hello !
Nice project ! Here are my profile detail
> Add of my personnal information in developpers.json

- developers.json
adding my profile info to the developers.json
> add profile

- src/Components/App.jsx
> Fix Search Input

- developers.json
- src/Components/App.jsx
I saw an [issue # 117](https://github.com/shreyas-a/awesome-developers/issues/117) you were facing while filtering the list of developers, I fixed that issue and tested it out and looks like it's working fine. Also, I added myself in the list of developers.json. 
Suggestion:
1. Please refactor your code by using static components it will simplify the render method of App.
> Fix for issue # 117 and add myself in developers.json
